/*
 * Copyright (c) 2026 Gerry Hull, W1VE
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction privileges...
 *
 * SPDX-License-Identifier: MIT
 */
namespace RWK.Shared;

/// <summary>
/// Identifies which input path produced an <see cref="EdgeEvent"/> (3.8).
/// </summary>
/// <remarks>
/// The source is carried with every edge so that arbitration decisions — notably
/// "paddle interrupts host" (3.7) — remain visible downstream, and so that logs can
/// attribute a stuck-key investigation to the correct input path.
/// <para>
/// This is descriptive only: the Station replays every edge identically regardless
/// of source.
/// </para>
/// _Requirements: 3.7, 3.8_
/// </remarks>
public enum EdgeSource
{
    /// <summary>Edge generated by the iambic/bug/straight-key paddle path.</summary>
    Paddle = 0,

    /// <summary>Edge generated by encoding buffered text from the WinKeyer host path.</summary>
    Host = 1,

    /// <summary>Edge generated by a WinKeyer immediate key-down/key-up command (2.4).</summary>
    Immediate = 2
}
